# .github/workflows/main-deploy.yml
# This workflow orchestrates the deployment of OIC Integrations to different environments.
# It now leverages a reusable workflow to avoid code duplication.

name: Deploy OIC Integrations - Build and Deploy

# Define when this workflow should run.
on:
  push:
    branches:
      - develop # Triggers on pushes to the 'develop' branch.
  pull_request:
    branches:
      - 'stage' # Triggers on pull requests to 'stage'.
      - 'develop' # Triggers on pull requests to 'develop'.
      - 'main' # Triggers on pull requests to 'main'.
    types:
      - closed # Only triggers when a pull request is closed (e.g., merged).
      
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI.
    inputs:
      iar_files_list:
        description: >-
          Comma-separated list of .iar file paths (e.g.,
          integrations/file1.iar,integrations/file2.iar). Overrides other
          inputs.
        required: false
        type: string
      iar_directory:
        description: >-
          Path to a directory containing .iar files (e.g., integrations/). Scans
          this directory.
        required: false
        type: string

# Environment variables accessible to all jobs in this workflow.
# OIC_URL is now passed as a secret to the reusable workflow for better security.
env:
  OIC_INSTANCE_NAME: '${{ vars.OIC_INSTANCE_NAME }}'

jobs:
  # New job to debug the OIC_INSTANCE_NAME variable directly from the main workflow's context.
  DebugVariables:
    runs-on: ubuntu-latest
    steps:
      - name: Print OIC_INSTANCE_NAME from Workflow Variables
        run: |
          echo "Debugging OIC_INSTANCE_NAME in main workflow:"
          echo "Value of OIC_INSTANCE_NAME from vars: '${{ vars.OIC_INSTANCE_NAME }}'"
          # If this prints an empty string, the variable is not set in GitHub's repository/organization variables.

  # Job to build and deploy to the 'dev' environment.
  BuildAndDeployToDev:
    # This job needs the DebugVariables job to complete first.
    needs: DebugVariables
    # This condition ensures the job runs only once per logical change to 'develop':
    # - Either a merged pull request to 'develop'
    # - Or a direct push (that is NOT a merge commit) to 'develop'
    if: |
      ${{
        github.ref == 'refs/heads/develop' &&
        (
          (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) ||
          (github.event_name == 'push' && github.event.head_commit.parents.length == 1)
        )
      }}
    
    # Call the reusable workflow for deployment.
    # The 'uses' keyword points to the path of the reusable workflow file.
    uses: ./.github/workflows/deploy-oic.yml
    
    # Pass inputs to the reusable workflow.
    with:
      target_environment: dev # Specify the target environment for the reusable workflow.
      iar_files_list: ${{ github.event.inputs.iar_files_list }} # Pass workflow_dispatch input.
      iar_directory: ${{ github.event.inputs.iar_directory }} # Pass workflow_dispatch input.
      oic_instance_name: ${{ vars.OIC_INSTANCE_NAME }} # Corrected: Pass OIC_INSTANCE_NAME directly from vars
    
    # Pass secrets to the reusable workflow.
    # All secrets used by the reusable workflow must be explicitly passed from the calling workflow.
    secrets:
      OIC_URL: ${{ secrets.OIC_URL }}
      OIC_TOKEN_URL: ${{ secrets.OIC_TOKEN_URL }}
      OIC_CLIENT_ID: ${{ secrets.OIC_CLIENT_ID }}
      OIC_CLIENT_SECRET: ${{ secrets.OIC_CLIENT_SECRET }}
      OIC_SCOPE: ${{ secrets.OIC_SCOPE }}

  # Job to build and deploy to the 'stage' environment.
  BuildAndDeployToStage:
    # This job needs the DebugVariables job to complete first.
    needs: DebugVariables
    # This condition ensures the job runs only once per logical change to 'stage':
    # - Either a merged pull request to 'stage'
    # - Or a direct push (that is NOT a merge commit) to 'stage'
    if: |
      ${{
        github.ref == 'refs/heads/stage' &&
        (
          (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) ||
          (github.event_name == 'push' && github.event.head_commit.parents.length == 1)
        )
      }}
    
    # Call the reusable workflow for deployment.
    uses: ./.github/workflows/deploy-oic.yml
    
    # Pass inputs to the reusable workflow.
    with:
      target_environment: stage # Specify the target environment for the reusable workflow.
      iar_files_list: ${{ github.event.inputs.iar_files_list }} # Pass workflow_dispatch input.
      iar_directory: ${{ github.event.inputs.iar_directory }} # Pass workflow_dispatch input.
      oic_instance_name: ${{ vars.OIC_INSTANCE_NAME }} # Corrected: Pass OIC_INSTANCE_NAME directly from vars
    
    # Pass secrets to the reusable workflow.
    secrets:
      OIC_URL: ${{ secrets.OIC_URL }}
      OIC_TOKEN_URL: ${{ secrets.OIC_TOKEN_URL }}
      OIC_CLIENT_ID: ${{ secrets.OIC_CLIENT_ID }}
      OIC_CLIENT_SECRET: ${{ secrets.OIC_CLIENT_SECRET }}
      OIC_SCOPE: ${{ secrets.OIC_SCOPE }}
